export const Frontendapi =[
    {
        name:"Ochi",
        link:"https://ochi-arpit.vercel.app",
        github:"https://github.com/Arpit10110/Ochi",
        techstack:["Html","CSS","JavaScript","React.js","locomotive","Gsap"]
    },
    {
        name:"Aniarpit",
        link:"https://aniarpit.vercel.app/",
        github:"https://github.com/Arpit10110/AniArpit",
        techstack:["Html","CSS","JavaScript","React.js","Consumet Api"]
    },
    {
        name:"PixFinder",
        link:"https://pixfinder-arpit.vercel.app",
        github:"https://github.com/Arpit10110/PixFinder",
        techstack:["Html","CSS","JavaScript","React.js","Unsplash api"]
    },
    {
        name:"Superhuman",
        link:"https://superhuman.onrender.com/",
        github:"https://github.com/Arpit10110/Superhuman",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Todo",
        link:"https://todo-arpit.onrender.com",
        github:"https://github.com/Arpit10110/Todo-List",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Animoda",
        link:"https://animoda.onrender.com",
        github:"https://github.com/Arpit10110/Animoda",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Movie-HUb",
        link:"https://moviehub-wi7l.onrender.com",
        github:"https://github.com/Arpit10110/MovieHub",
        techstack:["Html","CSS","JavaScript","React.js","OMDB Api"]
    },
    {
        name:"Coding Buddies",
        link:"https://codingbuddies.onrender.com",
        github:"https://github.com/Arpit10110/Coding-Buddies",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Jarvis",
        link:"https://jarvis-d7og.onrender.com",
        github:"https://github.com/Arpit10110/Chotu",
        techstack:["Html","CSS","JavaScript","React.js","AI integration"]
    },
    {
        name:"Chotu",
        link:"https://chotu-bkam.onrender.com",
        github:"https://github.com/Arpit10110/Jarvis",
        techstack:["Html","CSS","JavaScript","React.js","AI integration"]
    },
    {
        name:"Miband5",
        link:"https://miband5.onrender.com",
        github:"https://github.com/Arpit10110/mi-band-landing-page",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Instadownloader",
        link:"https://instadownloader-pjec.onrender.com",
        github:"https://github.com/Arpit10110/Insta-Video-Downloader",
        techstack:["Html","CSS","JavaScript","React.js","Rapid Api"]
    },
    {
        name:"Cocacola",
        link:"https://cocacola-70z0.onrender.com",
        github:"https://github.com/Arpit10110/CocaCola",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Dailyminds",
        link:"https://dailyminds.onrender.com",
        github:"https://github.com/Arpit10110/DailyMinds",
        techstack:["Html","CSS","JavaScript","React.js","News Api"]
    },
    {
        name:"Videocall",
        link:"https://videocall-arpit.onrender.com",
        github:"https://github.com/Arpit10110/VideoCall",
        techstack:["Html","CSS","JavaScript","React.js","ZegoCloud Api"]
    },
    {
        name:"Coinbaba",
        link:"https://coinbaba.onrender.com",
        github:"https://github.com/Arpit10110/CoinBaBa",
        techstack:["Html","CSS","JavaScript","React.js","Crypto Api"]
    },
    {
        name:"Codebro",
        link:"https://codebro.onrender.com",
        github:"https://github.com/Arpit10110/CodeBro",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Weather",
        link:"https://weather-pt5j.onrender.com",
        github:"https://github.com/Arpit10110/weather",
        techstack:["Html","CSS","JavaScript","React.js","Rapid Api"]
    },
    {
        name:"Fashionhub",
        link:"https://fashionhub-0.netlify.app",
        github:"https://github.com/Arpit10110/",
        techstack:["Html","CSS","JavaScript"]
    },
    {
        name:"Kaffen",
        link:"https://kaffen-coffee-and-beans.netlify.app",
        github:"https://github.com/Arpit10110/",
        techstack:["Html","CSS","JavaScript"]
    },
    {
        name:"Calculater",
        link:"https://calculaterop.netlify.app",
        github:"https://github.com/Arpit10110/",
        techstack:["Html","CSS","JavaScript"]
    },
    {
        name:"Raasta",
        link:"https://raasta-arpit.netlify.app",
        github:"https://github.com/Arpit10110/",
        techstack:["Html","CSS","JavaScript"]
    },
    {
        name:"Guess Game",
        link:"https://guess-the-n0.netlify.app",
        github:"https://github.com/Arpit10110/",
        techstack:["Html","CSS","JavaScript"]
    }
] 