export const FullstackApi =[
    {
        name:"HealthBridge",
        link:"https://healthbridges.vercel.app/",
        github:"https://github.com/Arpit10110/HealthBridge-frontend",
        techstack:["Html","CSS","JavaScript","React.js","Firebase","Node.js","Express.js","MongodB"]
    },
    {
        name:"Rangbazi",
        link:"https://rangbazi.vercel.app/",
        github:"https://github.com/Arpit10110/RangBazi-frontend",
        techstack:["Html","CSS","JavaScript","React.js","Firebase","Node.js","Express.js","MongodB"]
    },
    {
        name:"Khao Piyo",
        link:"https://khaopiyo.onrender.com",
        github:"https://github.com/Arpit10110/KhaoPiyo",
        techstack:["Html","CSS","JavaScript","React.js","Firebase"]
    },
    {
        name:"Bakebliss",
        link:"https://bakebliss.onrender.com",
        github:"https://github.com/Arpit10110/Bakebliss",
        techstack:["Html","CSS","JavaScript","React.js","Firebase","Node.js","Express.js","MongodB"]
    },
    {
        name:"Foodsegra",
        link:"https://foodsegra.onrender.com",
        github:"https://github.com/Arpit10110/Food-Segra",
        techstack:["Html","CSS","JavaScript","React.js","Firebase","Node.js","Express.js","MongodB"]
    },
    {
        name:"Animoda",
        link:"https://animoda.onrender.com",
        github:"https://github.com/Arpit10110/Animoda",
        techstack:["Html","CSS","JavaScript","React.js"]
    },
    {
        name:"Chitthi",
        link:"https://chitthi-by-arpit.onrender.com",
        github:"https://github.com/Arpit10110/Chitthi",
        techstack:["Html","CSS","JavaScript","React.js","Socket","Node.js","Express"]
    },
] 